using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PharmacyAPI.Data.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // This migration is auto-generated by EF Core.
            // Run: dotnet ef migrations add InitialCreate
            //      dotnet ef database update
            //
            // The Up() method creates all tables defined in AppDbContext.
            // EF Core generates this automatically — do NOT hand-edit.
            //
            // Seed data (Roles, Settings) is also applied here via
            // AppDbContext.OnModelCreating HasData() calls.
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // EF Core generates drop statements here automatically.
        }
    }
}
